### ISSUE TITLE
Current semester

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/agio-cli#27]
It would be nice to have a shortcut for automatically selecting the current semester of a course.

**Comment by awdeorio** [comment]
Brainstorm from a Slack conversation between @awdeorio and @japplefield :

```console
$ agio courses eecs485
$ agio courses eecs485current
$ agio courses --current
$ agio courses current
$ agio courses in-session
```

Of course, whatever shorthand we decide on would apply consistently to other subcommands, e.g.,
```console
$ agio submission --course current
```

**Comment by japplefield** [comment]
If the goal is for this to always narrow the course list down to exactly 1 course (or 0?) then `$ agio courses eecs485current` is the only one that makes sense for a user who teaches multiple courses currently. Is this a relevant case?
